apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiremock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiremock
  template:
    metadata:
      labels:
        app: wiremock
    spec:
      serviceAccountName: default
      containers:
        - name: wiremock
          image: registry-dev.artifactory.disfinal.com/mocks/wiremock:1.0.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: "3Gi"
            requests:
              cpu: "500m"
              memory: "2Gi"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wiremock-service
spec:
  selector:
    app: wiremock
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: wiremock-route
spec:
  host: app-wiremock.apps.aws-useast1-apps-dev-1.ocpdev.us-east-1.ac.disfinal.com
  to:
    kind: Service
    name: wiremock-service
  port:
    targetPort: 8080
